fun main (){
    val restaurantName = generateRestaurantName()
    println("Welcome to $restaurantName")
}

// generate a random restaurant name out of 100 options
fun generateRestaurantName(): String {
    val restaurantNames = listOf(
        "The Hungry Bear",
        "The Red Fox",
        "The Lazy Dog",
        "The Happy Pig",
        "The Clever Cat",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious Elephant",
        "The Clever Crow",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious Elephant",
        "The Clever Crow",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious Elephant",
        "The Clever Crow",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious Elephant",
        "The Clever Crow",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious Elephant",
        "The Clever Crow",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious Elephant",
        "The Clever Crow",
        "The Wise Owl",
        "The Brave Lion",
        "The Strong Tiger",
        "The Fast Cheetah",
        "The Sly Fox",
        "The Sneaky Snake",
        "The Friendly Dolphin",
        "The Playful Monkey",
        "The Curious")
    return restaurantNames.random()
}